name: CI - Frontend Unit Tests with Coverage and Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run frontend unit tests with coverage
        run: npm run test:coverage

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-allure-report
          path: frontend/allure-report

      - name: Upload Istanbul coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-code-coverage
          path: frontend/coverage
